In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [3]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
arr.shape

(3, 4)

In [5]:
#accessing specific elements of 2d array - array[rows, columns]
arr[1,3]

8

In [7]:
arr[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [9]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [24]:
# creating all 0s matrix
a = np.zeros((3,4), dtype = "int32")

In [25]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
#creating all 1s matrix

In [29]:
b = np.ones((4,5), dtype = "int32")

In [30]:
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [31]:
b[:, 0:3] =10

In [32]:
print(b)

[[10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [33]:
b[0:2, 3:5] = 4

In [34]:
print(b)

[[10 10 10  4  4]
 [10 10 10  4  4]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [35]:
b[2:4, 3:5] = 5

In [36]:
print(b)

[[10 10 10  4  4]
 [10 10 10  4  4]
 [10 10 10  5  5]
 [10 10 10  5  5]]


In [37]:
c = np.full(b.shape, 99)

In [38]:
print(c)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [41]:
d = np.full_like(c, 50)

In [42]:
print(d)

[[50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]]


In [43]:
n1 = np.ones((3,3), dtype = "int32")

In [44]:
print(n1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [45]:
n2 = np.full_like(n1, 2)

In [46]:
print(n2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [47]:
n3 = n1+n2

In [48]:
print(n3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [49]:
n = n3*n2

In [50]:
print(n)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [51]:
#creating 3d array

In [52]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [53]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [54]:
arr[0, 1, 1]

5

In [55]:
arr[0, : , 1:3]

array([[2, 3],
       [5, 6]])

In [56]:
arr[:, :, 1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [57]:
arr[:, :, 1:3] = 10

In [58]:
print(arr)

[[[ 1 10 10]
  [ 4 10 10]]

 [[ 7 10 10]
  [10 10 10]]]


In [60]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [61]:
b = a.reshape(2,6)

In [62]:
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [63]:
c = a.reshape(3,4)

In [64]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [65]:
d = a.reshape(2,3,2)
print(d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [66]:
#copying an array
x = a.copy()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [67]:
#copy v/s view
x[3:6] = 10

In [68]:
print(x)

[ 1  2  3 10 10 10  7  8  9 10 11 12]


In [69]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [70]:
y = a.view()
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [71]:
y[4:10] = 99

In [72]:
print(y)

[ 1  2  3  4 99 99 99 99 99 99 11 12]


In [73]:
print(a)

[ 1  2  3  4 99 99 99 99 99 99 11 12]


In [75]:
#iterating array's elements
for i in a:
    print(i+2)

3
4
5
6
101
101
101
101
101
101
13
14


In [76]:
#iteration in 2-d array
b = a.reshape(4,3)

In [77]:
for i in b:
    print(i)

[1 2 3]
[ 4 99 99]
[99 99 99]
[99 11 12]


In [78]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [81]:
c = np.concatenate((a,b), axis=0)

In [82]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [83]:
#joining 2-d array
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[7,8,9], [10,11,12]])


In [84]:
z = np.concatenate((x,y), axis = 0)#0 is for rows

In [85]:
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [86]:
w = np.concatenate((x,y), axis =1)
print(w)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [92]:
#sorting an array
arr1 = np.array([3,4,5,8,1,9,27,15,16,20,10,13])

In [88]:
arr2 = np.sort(arr1)

In [89]:
print(arr2)

[ 1  3  4  5  8  9 15 16 20 27]


In [91]:
#sorting 2-d array

In [94]:
a = arr1.reshape(3,4)
print(a)

[[ 3  4  5  8]
 [ 1  9 27 15]
 [16 20 10 13]]


In [96]:
b = np.sort(a)
print(b)

[[ 3  4  5  8]
 [ 1  9 15 27]
 [10 13 16 20]]
