In [1]:
import numpy as np
from numpy import random 

In [2]:
# generating 2-d float random array
float_array = random.rand(3,4)
print(float_array)

[[0.01045549 0.09933627 0.75977412 0.04228894]
 [0.72495291 0.06544507 0.38897324 0.48379061]
 [0.54341811 0.44129351 0.49105543 0.23956786]]


In [3]:
# selecting a random number from given array
rand_num = random.choice([2,3,4,5,7,8])
print(rand_num)

5


In [4]:
colors = ['red', ' green' , 'blue' ,'white' , 'black' , 'yellow' , 'pink', 'violet']
select_color = random.choice(colors)
print(select_color)

pink


In [5]:
security_breaches = np.array([[0,5,1],[0,2,9],[1,2,3],[2,2,1],[0,0,0]])
print(security_breaches)

[[0 5 1]
 [0 2 9]
 [1 2 3]
 [2 2 1]
 [0 0 0]]


In [6]:
print(security_breaches.sum())

28


In [7]:
print(security_breaches.sum(axis=1,keepdims = True))

[[ 6]
 [11]
 [ 6]
 [ 5]
 [ 0]]


## Multipling by a scalar

In [12]:
array = np.array([[1,2,3],[4,5,6]])
array*3
array1 = np.array([[1,2,3],[4,5,6]])

In [13]:
array*array1

array([[ 1,  4,  9],
       [16, 25, 36]])

# Not just for math

In [14]:
array = np.array([[1,2,3],[4,5,6]])
array > 2

array([[False, False,  True],
       [ True,  True,  True]])

# Vector Python Code!

In [15]:
array = np.array(["Numpy", "is" , "awesome"])
len(array) > 2

True